name: Dependabot

on:
  schedule:
    - cron: '0 12 * * *'   # exécution quotidienne à 12h UTC
  workflow_dispatch:       # permet un déclenchement manuel

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Dependabot
        uses: github/dependabot-action@main
        with:
          package-manager: pip
          directory: /                # racine du dépôt (où se trouve requirements.txt)
          target-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
